### PR TITLE
Configure Travis to Deploy Snapshots on commit to master

### LINKED ISSUE #86: Configure Travis to Deploy Snapshots on commit to master branch

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #86

### CODE REVIEW

**Comment by meltsufin** [comment]
@loosebazooka PTAL
I verified that it works using the previous commit to this branch.

**Comment by loosebazooka** [comment]
can you ensure it's only snapshots?

**Comment by meltsufin** [comment]
Maybe, but why? The master should never have a non-snapshot version. Even if it did, it would never make it out to Maven Central without additional steps.

**Comment by loosebazooka** [comment]
Well, either way a check would be nice. Can you file a bug and then :ski:

**Pull request merged**
