### PR TITLE
Credential file override flag support

### LINKED ISSUE #41: Allow passing in auth context to supported gcloud operations
For consumers of this API that can't rely on having to do `gcloud auth login` there needs to be a way to pass in the auth context.

An initial solution could be to support the `--credential-file-override` flag and require consumers to do the staging of the credential file themselves.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #41

### CODE REVIEW

**Comment by meltsufin** [comment]
LGTM

**Comment by etanshaul** [comment]
Want to merge in the builder first and I'll update this?

**Comment by meltsufin** [comment]
Sure, let me do that.

**Comment by etanshaul** [comment]
Updated to use builder.

**Comment by meltsufin** [comment]
:ship:

**Pull request merged**
