### PR TITLE
turn on travis

### PR DESCRIPTION
**Pull request by elharo**
@joaoandremartins as discussed in yesterday's meeting

### CODE REVIEW

**Comment by joaoandremartins** [comment]
Thanks Elliotte.

This fixes half of #2.

**Comment by meltsufin** [comment]
What's the status of this? Should we merge it in?

**Comment by elharo** [comment]
No, we need to make it pass first.

**Comment by meltsufin** [comment]
I rebased so that there is a src directory in the branch, but now I don't see Travis being invoked at all.

**Comment by elharo** [comment]
https://travis-ci.org/GoogleCloudPlatform/app-tools-lib-for-java

**Comment by elharo** [comment]
I think if we merge this then travis will start running.

On Wed, Apr 20, 2016 at 1:17 PM, meltsufin <notifications@github.com> wrote:

> I rebased so that there is a src directory in the branch, but now I don't
> see Travis being invoked at all.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/pull/6#issuecomment-212520386>
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by meltsufin** [comment]
Yes, I'm not sure why it's not kicking in for this branch. Let's trying merging it in.

**Pull request merged**
