### PR TITLE
Update codestyle with correct Java indent settings

### LINKED ISSUE #61: Fix IntelliJ codestyle settings

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #61.

Imported IntelliJ codestyle settings from here: https://github.com/google/styleguide/.
IntelliJ modified the original source after import, probably to fit the schema of the current version of the IDE.

### CODE REVIEW

**Comment by loosebazooka** [comment]
I think you just need to use the right file here. This works fine for me.

**Comment by loosebazooka** [comment]
Or update the styleguide file.

**Comment by meltsufin** [comment]
Hmmmm, I'm not sure what's going on with my codestyle settings then.

**Comment by loosebazooka** [comment]
It's possible I'm using a file from another source

**Comment by loosebazooka** [comment]
so lets :ship: for now and figure out what we want to do with .idea

**Pull request merged**
