### PR TITLE
version to 0.1.4

### PR DESCRIPTION
**Pull request by elharo**
@joaoandremartins

### CODE REVIEW

**Comment by joaoandremartins** [comment]
@elharo can you help me remember the reason for the version change?
Should we come up with a policy for changing versions, or is there one already?

**Comment by briandealwis** [comment]
There were some breaking changes that bit CT4E since we are pulling 0.1.3-SNAPSHOT.

  - `PathResolver.INSTANCE` removed
  - `CloudSdk.Builder.sdkPath(path)` argument type changes from `File` &rarr;  `Path`

> Should we come up with a policy for changing versions, or is there one already?

@elharo's proposing that CT4E use N-1 to shield us from breaking changes.  It'd be good if the library incremented the version on ABI or behavioural breaking changes.

**Comment by joaoandremartins** [comment]
LGTM

**Comment by elharo** [comment]
The proposal is that N-1 has a stable API while the current version can change. That way CT4E and CT4IJ can move when they're ready.

**Comment by meltsufin** [comment]
We normally bump the version right after a release. If you would like to avoid breaking changes, pull in a release version. Similarly, if you need to lock in certain changes, request a release. The master version is intended to always be {latest-release-version + 1}-SNAPSHOT.

**Pull request merged**
