### PR TITLE
Bump current version to 0.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by meltsufin**
...following the 0.1.0 release.

### CODE REVIEW

**Comment by meltsufin** [comment]
I wanted to reserve 0.1.x for emergency bug fixes that don't have breaking API changes.

**Comment by patflynn** [comment]
wouldn't this scheme limit us to 10 released API breaking revisions before
1.0?  One level deeper would give us more breathing room.

**Comment by meltsufin** [comment]
0.999.0 is still cool I think :)

**Comment by patflynn** [comment]
ah fair enough. Personally, I would like us to stay in the very lows <1 for
as long as possible to make it very clear to potential users that this is
not ready and very unstable.

**Comment by meltsufin** [comment]
Technically, with semantic versioning, we should be bumping the major version every time we make a breaking API change. However, since we want to stay below version 1.0.0, bumping the minor version instead seems like a reasonable compromise.

**Comment by patflynn** [comment]
a version of 0.9 means that something is close to 1.0 in people's minds.  I
don't want to get there any time soon.

**Comment by meltsufin** [comment]
Closing in favor of #142

**Pull request closed without merging**
